import { NextResponse } from "next/server";

const plans = [
  {
    id: "free",
    name: "Free",
    price: 0,
    currency: "USD",
    interval: "month",
    highlighted: false,
    popular: false,
    features: [
      "1 project",
      "1 GB storage",
      "10 GB bandwidth",
      "Community support",
    ],
    limits: {
      projects: 1,
      storage_gb: 1,
      bandwidth_gb: 10,
     团队成员: 1,
      deployments: 5,
      databases: 1,
      domains: 1,
    },
  },
  {
    id: "starter",
    name: "Starter",
    price: 19,
    currency: "USD",
    interval: "month",
    highlighted: false,
    popular: true,
    features: [
      "5 projects",
      "10 GB storage",
      "100 GB bandwidth",
      "Email support",
      "Custom domains",
      "SSL certificates",
    ],
    limits: {
      projects: 5,
      storage_gb: 10,
      bandwidth_gb: 100,
     团队成员: 3,
      deployments: 25,
      databases: 5,
      domains: 5,
    },
  },
  {
    id: "pro",
    name: "Pro",
    price: 49,
    currency: "USD",
    interval: "month",
    highlighted: true,
    popular: false,
    features: [
      "25 projects",
      "50 GB storage",
      "500 GB bandwidth",
      "Priority email support",
      "Custom domains",
      "SSL certificates",
      "Team collaboration",
      "API access",
    ],
    limits: {
      projects: 25,
      storage_gb: 50,
      bandwidth_gb: 500,
     团队成员: 10,
      deployments: 100,
      databases: 25,
      domains: 25,
    },
  },
  {
    id: "business",
    name: "Business",
    price: 149,
    currency: "USD",
    interval: "month",
    highlighted: false,
    popular: false,
    features: [
      "100 projects",
      "250 GB storage",
      "2 TB bandwidth",
      "Priority support",
      "Custom domains",
      "SSL certificates",
      "Team collaboration",
      "API access",
      "Advanced analytics",
      "SLA guarantee",
    ],
    limits: {
      projects: 100,
      storage_gb: 250,
      bandwidth_gb: 2000,
     团队成员: 25,
      deployments: 500,
      databases: 100,
      domains: 100,
    },
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: 499,
    currency: "USD",
    interval: "month",
    highlighted: false,
    popular: false,
    features: [
      "Unlimited projects",
      "1 TB storage",
      "10 TB bandwidth",
      "Dedicated support",
      "Custom domains",
      "SSL certificates",
      "Team collaboration",
      "API access",
      "Advanced analytics",
      "SLA guarantee",
      "SSO / SAML",
      "Custom integrations",
    ],
    limits: {
      projects: -1,
      storage_gb: 1024,
      bandwidth_gb: 10240,
     团队成员: -1,
      deployments: -1,
      databases: -1,
      domains: -1,
    },
  },
];

export async function GET() {
  return NextResponse.json(plans);
}
