import { pgTable, uuid, text, timestamp, integer, boolean, jsonb, decimal } from "drizzle-orm/pg-core";
import { users } from "./users";

// Dedicated Servers
export const dedicatedServers = pgTable("dedicated_servers", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").references(() => users.id).notNull(),
  name: text("name").notNull(),
  plan: text("plan").notNull(),
  cpu: text("cpu").notNull(),
  ram: text("ram").notNull(),
  storage: text("storage").notNull(),
  bandwidth: text("bandwidth"),
  ipCount: integer("ip_count").default(1),
  ips: text("ips").array(),
  os: text("os"),
  location: text("location"),
  provider: text("provider"),
  status: text("status").notNull().default("provisioning"),
  price: decimal("price", { precision: 10, scale: 2 }),
  managed: boolean("managed").default(false),
  autoRenew: boolean("auto_renew").default(true),
  provisionedAt: timestamp("provisioned_at"),
  expiresAt: timestamp("expires_at"),
  lastRebootedAt: timestamp("last_rebooted_at"),
  metrics: jsonb("metrics"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const dedicatedServerPlans = pgTable("dedicated_server_plans", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  cpu: text("cpu").notNull(),
  cpuCores: integer("cpu_cores").notNull(),
  ram: text("ram").notNull(),
  ramGb: integer("ram_gb").notNull(),
  storage: text("storage").notNull(),
  storageGb: integer("storage_gb").notNull(),
  storageType: text("storage_type").default("NVMe SSD"),
  bandwidth: text("bandwidth"),
  bandwidthTb: integer("bandwidth_tb"),
  ipCount: integer("ip_count").default(1),
  location: text("location"),
  price: decimal("price", { precision: 10, scale: 2 }).notNull(),
  setupFee: decimal("setup_fee", { precision: 10, scale: 2 }).default("0"),
  managedPrice: decimal("managed_price", { precision: 10, scale: 2 }),
  inStock: boolean("in_stock").default(true),
  popular: boolean("popular").default(false),
  active: boolean("active").default(true),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Migration Tools
export const siteMigrations = pgTable("site_migrations", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").references(() => users.id).notNull(),
  type: text("type").notNull(),
  sourceUrl: text("source_url"),
  sourceType: text("source_type"),
  targetUrl: text("target_url"),
  targetType: text("target_type").notNull().default("cloudhost"),
  status: text("status").notNull().default("pending"),
  progress: integer("progress").default(0),
  filesTransferred: integer("files_transferred").default(0),
  totalFiles: integer("total_files").default(0),
  dataSize: text("data_size"),
  estimatedTime: integer("estimated_time").default(0),
  startedAt: timestamp("started_at"),
  completedAt: timestamp("completed_at"),
  errorLog: jsonb("error_log"),
  plugin: text("plugin"),
  preserveSettings: boolean("preserve_settings").default(true),
  preserveContent: boolean("preserve_content").default(true),
  preserveUsers: boolean("preserve_users").default(true),
  sslMigration: boolean("ssl_migration").default(true),
  incrementalSync: boolean("incremental_sync").default(false),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Website Security
export const websiteSecurity = pgTable("website_security", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").references(() => users.id).notNull(),
  domain: text("domain").notNull(),
  plan: text("plan").notNull().default("basic"),
  status: text("status").notNull().default("active"),
  lastScan: timestamp("last_scan"),
  scanFrequency: text("scan_frequency").default("daily"),
  vulnerabilities: integer("vulnerabilities").default(0),
  criticalCount: integer("critical_count").default(0),
  highCount: integer("high_count").default(0),
  mediumCount: integer("medium_count").default(0),
  lowCount: integer("low_count").default(0),
  malwareDetected: boolean("malware_detected").default(false),
  blacklisted: boolean("blacklisted").default(false),
  firewall: boolean("firewall").default(false),
  autoFix: boolean("auto_fix").default(false),
  emailAlerts: boolean("email_alerts").default(true),
  price: decimal("price", { precision: 10, scale: 2 }),
  activatedAt: timestamp("activated_at").defaultNow(),
  expiresAt: timestamp("expires_at"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const securityFindings = pgTable("security_findings", {
  id: uuid("id").defaultRandom().primaryKey(),
  securityId: uuid("security_id").references(() => websiteSecurity.id).notNull(),
  type: text("type").notNull(),
  severity: text("severity").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  path: text("path"),
  recommendation: text("recommendation"),
  status: text("status").notNull().default("open"),
  autoFixed: boolean("auto_fixed").default(false),
  detectedAt: timestamp("detected_at").defaultNow(),
  resolvedAt: timestamp("resolved_at"),
});

// Fix Hacked Website (SOS)
export const hackedWebsiteSos = pgTable("hacked_website_sos", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").references(() => users.id).notNull(),
  domain: text("domain").notNull(),
  severity: text("severity").notNull().default("medium"),
  status: text("status").notNull().default("reported"),
  description: text("description"),
  symptoms: jsonb("symptoms"),
  malwareType: text("malware_type"),
  infectionDate: timestamp("infection_date"),
  filesAffected: integer("files_affected").default(0),
  filesCleaned: integer("files_cleaned").default(0),
  totalFiles: integer("total_files").default(0),
  backupRestored: boolean("backup_restored").default(false),
  backupDate: timestamp("backup_date"),
  securityPatches: jsonb("security_patches"),
  price: decimal("price", { precision: 10, scale: 2 }),
  assignedTechnician: text("assigned_technician"),
  reportedAt: timestamp("reported_at").defaultNow(),
  startedAt: timestamp("started_at"),
  completedAt: timestamp("completed_at"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Anti-Spam Protection
export const antiSpamProtection = pgTable("anti_spam_protection", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").references(() => users.id).notNull(),
  domain: text("domain").notNull(),
  status: text("status").notNull().default("active"),
  spamScore: integer("spam_score").default(0),
  emailsBlocked: integer("emails_blocked").default(0),
  emailsQuarantined: integer("emails_quarantined").default(0),
  emailsAllowed: integer("emails_allowed").default(0),
  rules: jsonb("rules"),
  whitelist: text("whitelist").array(),
  blacklist: text("blacklist").array(),
  dkimEnabled: boolean("dkim_enabled").default(false),
  spfEnabled: boolean("spf_enabled").default(false),
  dmarcEnabled: boolean("dmarc_enabled").default(false),
  quarantineSpam: boolean("quarantine_spam").default(true),
  blockMalware: boolean("block_malware").default(true),
  blockPhishing: boolean("block_phishing").default(true),
  price: decimal("price", { precision: 10, scale: 2 }),
  activatedAt: timestamp("activated_at").defaultNow(),
  expiresAt: timestamp("expires_at"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// FastVPN
export const fastVpn = pgTable("fast_vpn", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").references(() => users.id).notNull(),
  plan: text("plan").notNull().default("basic"),
  status: text("status").notNull().default("active"),
  protocol: text("protocol").default("wireguard"),
  serverLocation: text("server_location"),
  serverIp: text("server_ip"),
  assignedIp: text("assigned_ip"),
  port: integer("port"),
  publicKey: text("public_key"),
  privateKey: text("private_key"),
  bandwidthUsed: text("bandwidth_used").default("0 GB"),
  bandwidthLimit: text("bandwidth_limit").default("100 GB"),
  connectedDevices: integer("connected_devices").default(0),
  maxDevices: integer("max_devices").default(5),
  killSwitch: boolean("kill_switch").default(false),
  splitTunneling: boolean("split_tunneling").default(false),
  obfuscation: boolean("obfuscation").default(false),
  autoConnect: boolean("auto_connect").default(false),
  dnsLeakProtection: boolean("dns_leak_protection").default(true),
  price: decimal("price", { precision: 10, scale: 2 }),
  activatedAt: timestamp("activated_at").defaultNow(),
  expiresAt: timestamp("expires_at"),
  lastConnectedAt: timestamp("last_connected_at"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const vpnLocations = pgTable("vpn_locations", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  country: text("country").notNull(),
  countryCode: text("country_code").notNull(),
  city: text("city"),
  serverCount: integer("server_count").default(1),
  latency: integer("latency"),
  load: integer("load").default(0),
  active: boolean("active").default(true),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Cyber Insurance
export const cyberInsurance = pgTable("cyber_insurance", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").references(() => users.id).notNull(),
  plan: text("plan").notNull(),
  status: text("status").notNull().default("active"),
  coverage: text("coverage"),
  coverageAmount: decimal("coverage_amount", { precision: 12, scale: 2 }),
  deductible: decimal("deductible", { precision: 10, scale: 2 }),
  premium: decimal("premium", { precision: 10, scale: 2 }),
  paymentFrequency: text("payment_frequency").default("monthly"),
  startDate: timestamp("start_date"),
  endDate: timestamp("end_date"),
  autoRenew: boolean("auto_renew").default(true),
  policyNumber: text("policy_number"),
  insuredAssets: jsonb("insured_assets"),
  coverageTypes: jsonb("coverage_types"),
  claimsCount: integer("claims_count").default(0),
  totalClaimed: decimal("total_claimed", { precision: 12, scale: 2 }),
  riskLevel: text("risk_level").default("medium"),
  industry: text("industry"),
  companySize: text("company_size"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const insuranceClaims = pgTable("insurance_claims", {
  id: uuid("id").defaultRandom().primaryKey(),
  policyId: uuid("policy_id").references(() => cyberInsurance.id).notNull(),
  userId: uuid("user_id").references(() => users.id).notNull(),
  type: text("type").notNull(),
  status: text("status").notNull().default("filed"),
  incidentDate: timestamp("incident_date"),
  filedAt: timestamp("filed_at").defaultNow(),
  description: text("description"),
  amount: decimal("amount", { precision: 12, scale: 2 }),
  approvedAmount: decimal("approved_amount", { precision: 12, scale: 2 }),
  evidence: jsonb("evidence"),
  notes: text("notes"),
  resolvedAt: timestamp("resolved_at"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Public DNS Resolver
export const publicDnsResolver = pgTable("public_dns_resolver", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").references(() => users.id),
  queryDomain: text("query_domain").notNull(),
  queryType: text("query_type").default("A"),
  result: jsonb("result"),
  responseTime: integer("response_time"),
  sourceIp: text("source_ip"),
  queriedAt: timestamp("queried_at").defaultNow().notNull(),
});
