import { pgTable, text, timestamp, uuid, boolean, jsonb, integer } from "drizzle-orm/pg-core";
import { users } from "./users";
import { organizations } from "./projects";

export const images = pgTable("images", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").references(() => users.id).notNull(),
  organizationId: uuid("organization_id").references(() => organizations.id),
  name: text("name").notNull(),
  filename: text("filename"),
  contentType: text("content_type"),
  size: integer("size"),
  width: integer("width"),
  height: integer("height"),
  variants: jsonb("variants").default([]),
  variantConfigs: jsonb("variant_configs").default([]),
  transformations: jsonb("transformations").default([]),
  blurhash: text("blurhash"),
  metadata: jsonb("metadata").default({}),
  deliveryUrls: jsonb("delivery_urls").default({}),
  usage: jsonb("usage").default({ requests: 0, bandwidth: 0 }),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const streams = pgTable("streams", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").references(() => users.id).notNull(),
  organizationId: uuid("organization_id").references(() => organizations.id),
  title: text("title").notNull(),
  description: text("description"),
  filename: text("filename"),
  duration: integer("duration"),
  size: integer("size"),
  status: text("status").default("processing"),
  inputType: text("input_type").default("video"),
  playbackUrl: text("playback_url"),
  previewUrl: text("preview_url"),
  thumbnailUrl: text("thumbnail_url"),
  readyToStream: boolean("ready_to_stream").default(false),
  allowedOrigins: jsonb("allowed_origins").default([]),
  requireSignedUrls: boolean("require_signed_urls").default(false),
  signedSecret: text("signed_secret"),
  meta: jsonb("meta").default({}),
  subtitles: jsonb("subtitles").default([]),
  chapters: jsonb("chapters").default([]),
  liveInput: jsonb("live_input").default({}),
  recording: jsonb("recording").default({ mode: "automatic", timeoutSeconds: 0 }),
  watermark: jsonb("watermark").default({}),
  usage: jsonb("usage").default({ views: 0, watchTime: 0, bandwidth: 0 }),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const realtimeKit = pgTable("realtime_kit", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: uuid("user_id").references(() => users.id).notNull(),
  organizationId: uuid("organization_id").references(() => organizations.id),
  name: text("name").notNull(),
  appType: text("app_type").default("messaging"),
  tokens: jsonb("tokens").default([]),
  connections: jsonb("connections").default([]),
  connectionCount: integer("connection_count").default(0),
  maxConnections: integer("max_connections").default(100),
  allowedOrigins: jsonb("allowed_origins").default([]),
  webhookUrl: text("webhook_url"),
  turnConfig: jsonb("turn_config").default({ servers: [], username: "", credential: "" }),
  sfuConfig: jsonb("sfu_config").default({ enabled: false, maxPublishers: 10, maxSubscribers: 100 }),
  usage: jsonb("usage").default({ connections: 0, messages: 0, bandwidth: 0 }),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});
